apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator-x.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcachedx is the Schema for the memcachedxes API
      displayName: Memcachedx
      kind: Memcachedx
      name: memcachedxes.cache.akihikokuroda
      version: v1alpha1
  description: memcached-x
  displayName: memcached-x
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Memcached Operator X
    url: https://memcached-operator-x.domain
  maintainers:
  - email: akihikokuroda
    name: name
  maturity: alpha
  provider:
    name: memcached-x
  version: 0.0.0
